In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
# Load Data
df = pd.read_csv('BDataF.csv')
df_test = pd.read_csv('BDataTest.csv')

# Dropping unwanted columns
#cols_to_drop = ['BachelorAge', 'HairColor', 'HairType', 'Hometown']
#test_cols_to_drop = ['BachelorAge']
#df.drop(cols_to_drop, axis=1, inplace=True)
#df_test.drop(test_cols_to_drop, axis=1, inplace=True)

# Renaming Dummy Columns
df = pd.concat([df, pd.get_dummies(df['DateRose'], prefix='DateRose')], axis=1)
df_test = pd.concat([df_test, pd.get_dummies(df_test['DateRose'], prefix='DateRose')], axis=1)


BachelorData = df
BachelorTestData = df_test

In [ ]:
# List column names for feature selection
list(BachelorData)

In [4]:
# Linear Regression using scikit-learn
feature_cols = ['FirstImpressionRose', 'DateRose', 'OlderthanBachelor', 'YoungerthanBachelor', 'SameAgeasBachelor', 'DateRose_0', 'DateRose_1', 'DateRose_2']

X = BachelorData[feature_cols]
y = BachelorData['Winner']

from sklearn.linear_model import LinearRegression
lm = LinearRegression()
lm.fit(X, y)

# Print the Intercepts and Coefficients
print lm.intercept_
print lm.coef_

# Pair feature names withcoefficients
coefficients = zip(feature_cols, lm.coef_)

# R Squared value
lm.score(X, y)

coefficients

0.555214972193
[-0.04476471 -0.13936282 -0.01658894  0.00223632  0.02669656 -0.55521497
 -0.31414996 -0.10110259]

[('FirstImpressionRose', -0.044764711941878581),
 ('DateRose', -0.13936282375630996),
 ('OlderthanBachelor', -0.016588939343129164),
 ('YoungerthanBachelor', 0.0022363228326662829),
 ('SameAgeasBachelor', 0.026696556538492334),
 ('DateRose_0', -0.55521497219257421),
 ('DateRose_1', -0.31414995674849572),
 ('DateRose_2', -0.10110259334090232)]

In [5]:
# Make predictions for feature_cols_test and store them/print them
feature_cols_test = ['FirstImpressionRose', 'DateRose', 'OlderthanBachelor', 'YoungerthanBachelor', 'SameAgeasBachelor', 'DateRose_0', 'DateRose_1', 'DateRose_2']

X_new = BachelorTestData[feature_cols_test]
BachelorTestData['Predictions'] = lm.predict(X_new)

BachelorTestData

,Name,Age,Season,FirstImpressionRose,DateRose,FirstName,LastName,State,AbsDistFromBachelorAge,RelDistFromBachelorAge,...,AbsDistFromBacheloretteAge,OlderThanBachelorette,YoungerThanBachelorette,SameAgeasBachelorette,BacheloretteRace,SameRaceasBachelorette,DateRose_0,DateRose_1,DateRose_2,Predictions
0,Brittany Farrar,26,21,0,0,Brittany,Farrar,California,10,10,...,1,1,0,0,White,1,1.0,0.0,0.0,0.002236
1,Whitney Fransway,25,21,0,0,Whitney,Fransway,Minnesota,11,11,...,0,0,0,1,White,1,1.0,0.0,0.0,0.002236
2,Raven Gates,25,21,0,1,Raven,Gates,Arkansas,11,11,...,0,0,0,1,White,1,0.0,1.0,0.0,0.103939
3,Jasmine Goode,29,21,0,0,Jasmine,Goode,New Jersey,7,7,...,4,1,0,0,White,0,1.0,0.0,0.0,0.002236
4,Vanessa Grimaldi,29,21,0,1,Vanessa,Grimaldi,Canada,7,7,...,4,1,0,0,White,1,0.0,1.0,0.0,0.103939
5,Jaimi King,28,21,0,0,Jaimi,King,Louisiana,8,8,...,3,1,0,0,White,0,1.0,0.0,0.0,0.002236
6,Rachel Lindsay,31,21,1,1,Rachel,Lindsay,Texas,5,5,...,6,1,0,0,White,0,0.0,1.0,0.0,0.059174
7,Astrid Loch,26,21,0,0,Astrid,Loch,Florida,10,10,...,1,1,0,0,White,1,1.0,0.0,0.0,0.002236
8,Danielle Lombard,27,21,0,2,Danielle,Lombard,California,9,9,...,2,1,0,0,White,0,0.0,0.0,1.0,0.177623
9,Danielle Maltby,31,21,0,1,Danielle,Maltby,Wisconsin,5,5,...,6,1,0,0,White,1,0.0,1.0,0.0,0.103939
10,Taylor Nolan,23,21,0,0,Taylor,Nolan,Washington,13,13,...,2,0,1,0,White,0,1.0,0.0,0.0,0.002236
11,Corinne Olympios,24,21,0,1,Corinne,Olympios,Florida,12,12,...,1,0,1,0,White,1,0.0,1.0,0.0,0.103939
12,Kristina Schulman,24,21,0,1,Kristina,Schulman,Kentucky,12,12,...,1,0,1,0,White,1,0.0,1.0,0.0,0.103939
13,Josephine Tutman,24,21,0,0,Josephine,Tutman,California,12,12,...,1,0,1,0,White,1,1.0,0.0,0.0,0.002236
14,Sarah Vendal,26,21,0,0,Sarah,Vendal,California,10,10,...,1,1,0,0,White,1,1.0,0.0,0.0,0.002236
15,Alexis Waters,23,21,0,0,Alexis,Waters,New Jersey,13,13,...,2,0,1,0,White,1,1.0,0.0,0.0,0.002236
16,Christen Whitney,25,21,0,1,Christen,Whitney,Indiana,11,11,...,0,0,0,1,White,1,0.0,1.0,0.0,0.103939
17,Dominique Alexis,25,21,0,0,Dominique,Alexis,California,11,11,...,0,0,0,1,White,0,1.0,0.0,0.0,0.002236
18,Lacey Mark,25,21,0,0,Lacey,Mark,New Jersey,11,11,...,0,0,0,1,White,1,1.0,0.0,0.0,0.002236
19,Hailey Merkt,23,21,0,0,Hailey,Merkt,Canada,13,13,...,2,0,1,0,White,1,1.0,0.0,0.0,0.002236
20,Elizabeth Whitelaw,24,21,0,0,Elizabeth,Whitelaw,Illinois,12,12,...,1,0,1,0,White,1,1.0,0.0,0.0,0.002236
21,Elizabeth Sandoz,29,21,0,0,Elizabeth,Sandoz,Nebraska,7,7,...,4,1,0,0,White,1,1.0,0.0,0.0,0.002236
22,Angela Amezcua,26,21,0,0,Angela,Amezcua,Maryland,10,10,...,1,1,0,0,White,1,1.0,0.0,0.0,0.002236
23,Jasmine Brown,25,21,0,0,Jasmine,Brown,Washington,11,11,...,0,0,0,1,White,0,1.0,0.0,0.0,0.002236
24,Olivia Burnette,25,21,0,0,Olivia,Burnette,Alaska,11,11,...,0,0,0,1,White,0,1.0,0.0,0.0,0.002236
25,Ida Marie DeLosSantos,23,21,0,0,Ida Marie,DeLosSantos,Texas,13,13,...,2,0,1,0,White,1,1.0,0.0,0.0,0.002236
26,Briana Guertler,28,21,0,0,Briana,Guertler,Utah,8,8,...,3,1,0,0,White,1,1.0,0.0,0.0,0.002236
27,Lauren Hussey,30,21,0,0,Lauren,Hussey,Florida,6,6,...,5,1,0,0,White,1,1.0,0.0,0.0,0.002236
28,Susannah Milan,26,21,0,0,Susannah,Milan,California,10,10,...,1,1,0,0,White,1,1.0,0.0,0.0,0.002236
29,Michelle Ramkissoon,24,21,0,0,Michelle,Ramkissoon,California,12,12,...,1,0,1,0,White,0,1.0,0.0,0.0,0.002236

In [6]:
BachelorTestData[BachelorTestData.Predictions > .1]

,Name,Age,Season,FirstImpressionRose,DateRose,FirstName,LastName,State,AbsDistFromBachelorAge,RelDistFromBachelorAge,...,AbsDistFromBacheloretteAge,OlderThanBachelorette,YoungerThanBachelorette,SameAgeasBachelorette,BacheloretteRace,SameRaceasBachelorette,DateRose_0,DateRose_1,DateRose_2,Predictions
2,Raven Gates,25,21,0,1,Raven,Gates,Arkansas,11,11,...,0,0,0,1,White,1,0.0,1.0,0.0,0.103939
4,Vanessa Grimaldi,29,21,0,1,Vanessa,Grimaldi,Canada,7,7,...,4,1,0,0,White,1,0.0,1.0,0.0,0.103939
8,Danielle Lombard,27,21,0,2,Danielle,Lombard,California,9,9,...,2,1,0,0,White,0,0.0,0.0,1.0,0.177623
9,Danielle Maltby,31,21,0,1,Danielle,Maltby,Wisconsin,5,5,...,6,1,0,0,White,1,0.0,1.0,0.0,0.103939
11,Corinne Olympios,24,21,0,1,Corinne,Olympios,Florida,12,12,...,1,0,1,0,White,1,0.0,1.0,0.0,0.103939
12,Kristina Schulman,24,21,0,1,Kristina,Schulman,Kentucky,12,12,...,1,0,1,0,White,1,0.0,1.0,0.0,0.103939
16,Christen Whitney,25,21,0,1,Christen,Whitney,Indiana,11,11,...,0,0,0,1,White,1,0.0,1.0,0.0,0.103939

In [7]:
BachelorData['Predictions'] = lm.predict(X)
BachelorData

,Name,Age,Outcome,Season,FirstImpressionRose,DateRose,FirstName,LastName,State,Winner,...,OlderThanBachelorette,YoungerThanBachelorette,SameAgeasBachelorette,SameRaceasBachelorette,DateRose_0,DateRose_1,DateRose_2,DateRose_3,DateRose_4,Predictions
0,Amanda Kremer,28,Week 2,20,0,0,Amanda,Kremer,Oregon,0,...,1,0,0,1,1.0,0.0,0.0,0.0,0.0,-0.016589
1,Amanda Stanton,25,Week 8,20,0,3,Amanda,Stanton,California,0,...,1,0,0,1,0.0,0.0,0.0,1.0,0.0,0.139363
2,Amber James,30,Week 4,20,0,1,Amber,James,Illinois,0,...,0,1,0,0,0.0,1.0,0.0,0.0,0.0,0.085113
3,Becca Tilley,26,Week 7,20,0,1,Becca,Tilley,Louisiana,0,...,1,0,0,1,0.0,1.0,0.0,0.0,0.0,0.128399
4,Breanne Rice,30,Week 1,20,0,0,Breanne,Rice,Washington,0,...,0,1,0,1,1.0,0.0,0.0,0.0,0.0,-0.016589
5,Caila Quinn,24,Week 9,20,0,2,Caila,Quinn,Ohio,0,...,1,0,0,0,0.0,0.0,1.0,0.0,0.0,0.177623
6,Emily Ferguson,23,Week 7,20,0,1,Emily,Ferguson,Nevada,0,...,1,0,0,1,0.0,1.0,0.0,0.0,0.0,0.103939
7,Haley Ferguson,23,Week 4,20,0,0,Haley,Ferguson,Nevada,0,...,1,0,0,1,1.0,0.0,0.0,0.0,0.0,0.002236
8,Isabel Goodkind,24,Week 1,20,0,0,Isabel,Goodkind,Connecticut,0,...,1,0,0,1,1.0,0.0,0.0,0.0,0.0,0.002236
9,Jackie Dion,23,Week 2,20,0,0,Jackie,Dion,California,0,...,1,0,0,1,1.0,0.0,0.0,0.0,0.0,0.002236
10,Jami Letain,23,Week 3,20,0,0,Jami,Letain,Alberta,0,...,1,0,0,0,1.0,0.0,0.0,0.0,0.0,0.002236
11,Jennifer Saviano,25,Week 5,20,0,0,Jennifer,Saviano,Florida,0,...,1,0,0,1,1.0,0.0,0.0,0.0,0.0,0.002236
12,Jessica Moser,23,Week 1,20,0,0,Jessica,Moser,Florida,0,...,1,0,0,1,1.0,0.0,0.0,0.0,0.0,0.002236
13,JoJo Fletcher,24,Runner-up,20,0,2,JoJo,Fletcher,Texas,0,...,1,0,0,1,0.0,0.0,1.0,0.0,0.0,0.177623
14,Jubilee Sharpe,24,Week 5,20,0,1,Jubilee,Sharpe,Florida,0,...,1,0,0,0,0.0,1.0,0.0,0.0,0.0,0.103939
15,Lace Morris,25,Week 3,20,0,0,Lace,Morris,Colorado,0,...,1,0,0,1,1.0,0.0,0.0,0.0,0.0,0.002236
16,Laura Esselman,24,Week 1,20,0,0,Laura,Esselman,Kentucky,0,...,1,0,0,1,1.0,0.0,0.0,0.0,0.0,0.002236
17,Lauren Barr,23,Week 2,20,0,0,Lauren,Barr,Oklahoma,0,...,1,0,0,1,1.0,0.0,0.0,0.0,0.0,0.002236
18,Lauren Bushnell,25,Winner,20,0,2,Lauren,Bushnell,Oregon,1,...,1,0,0,1,0.0,0.0,1.0,0.0,0.0,0.177623
19,Lauren Himle,25,Week 6,20,0,1,Lauren,Himle,Michigan,0,...,1,0,0,1,0.0,1.0,0.0,0.0,0.0,0.103939
20,Lauren Russell,26,Week 1,20,0,0,Lauren,Russell,Texas,0,...,1,0,0,1,1.0,0.0,0.0,0.0,0.0,0.026697
21,Leah Block,25,Week 6,20,0,0,Leah,Block,Colorado,0,...,1,0,0,1,1.0,0.0,0.0,0.0,0.0,0.002236
22,Maegan Miller,30,Week 1,20,0,0,Maegan,Miller,California,0,...,0,1,0,1,1.0,0.0,0.0,0.0,0.0,-0.016589
23,Olivia Caridi,23,Week 6,20,1,2,Olivia,Caridi,Virginia,0,...,1,0,0,1,0.0,0.0,1.0,0.0,0.0,0.132858
24,Rachel Tchen,23,Week 4,20,0,0,Rachel,Tchen,Arkansas,0,...,1,0,0,0,1.0,0.0,0.0,0.0,0.0,0.002236
25,Samantha Passmore,26,Week 2,20,0,0,Samantha,Passmore,Florida,0,...,1,0,0,1,1.0,0.0,0.0,0.0,0.0,0.026697
26,Shushanna Mkrtychyan,27,Week 3,20,0,0,Shushanna,Mkrtychyan,Utah,0,...,1,0,0,1,1.0,0.0,0.0,0.0,0.0,-0.016589
27,Tiara Soleim,27,Week 1,20,0,0,Tiara,Soleim,Washington,0,...,1,0,0,1,1.0,0.0,0.0,0.0,0.0,-0.016589
28,Alissa Giambrone,24,Week 2,19,0,0,Alissa,Giambrone,New Jersey,0,...,1,0,0,1,1.0,0.0,0.0,0.0,0.0,0.002236
29,Amanda Goerlitz,24,Week 1,19,0,0,Amanda,Goerlitz,Illinois,0,...,1,0,0,1,1.0,0.0,0.0,0.0,0.0,0.002236
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,Sarah Newlon,23,Week 3,11,0,1,Sarah,Newlon,Illinois,0,...,1,0,0,0,0.0,1.0,0.0,0.0,0.0,0.103939
262,Sheena Stewart[3],23,Week 6,11,0,0,Sheena,Stewart[3],California,0,...,1,0,0,0,1.0,0.0,0.0,0.0,0.0,0.002236
263,Solisa Shoop[9],25,Week 3,11,0,0,Solisa,Shoop[9],Texas,0,...,1,0,0,0,1.0,0.0,0.0,0.0,0.0,0.002236
264,Susan Stein,35,Week 1,11,0,0,Susan,Stein,Illinois,0,...,0,1,0,0,1.0,0.0,0.0,0.0,0.0,0.026697
265,Tauni Nessler [11],31,Week 1,11,0,0,Tauni,Nessler,Minnesota,0,...,0,1,0,0,1.0,0.0,0.0,0.0,0.0,0.002236
266,Alexis Young,26,Week 2,10,0,0,Alexis,Young,TX,0,...,0,0,0,0,1.0,0.0,0.0,0.0,0.0,0.002236
267,Amanda Hackney,26,Week 3,10,0,0,Amanda,Hackney,TX,0,...,0,0,0,0,1.0,0.0,0.0,0.0,0.0,0.002236
268,Amber Alchalabi,23,Week 6,10,0,2,Amber,Alchalabi,Texas,0,...,0,0,0,0,0.0,0.0,1.0,0.0,0.0,0.177623
269,Bevin Nicole Powers,28,Week 8,10,0,2,Bevin,Powers,California,0,...,0,0,0,0,0.0,0.0,1.0,0.0,0.0,0.177623
270,Blakeney Rowe,29,Week 1,10,0,0,Blakeney,Rowe,AL,0,...,0,0,0,0,1.0,0.0,0.0,0.0,0.0,0.026697
271,Candace DeCost,23,Week 1,10,0,0,Candace,DeCost,SC,0,...,0,0,0,0,1.0,0.0,0.0,0.0,0.0,0.002236
272,Catherine Warren,23,Week 1,10,0,0,Catherine,Warren,IL,0,...,0,0,0,0,1.0,0.0,0.0,0.0,0.0,0.002236
273,Danielle Imwalle,25,Week 7,10,0,0,Danielle,Imwalle,Connecticut,0,...,0,0,0,0,1.0,0.0,0.0,0.0,0.0,0.002236
274,Danielle Vallis,26,Week 1,10,0,0,Danielle,Vallis,NY,0,...,0,0,0,0,1.0,0.0,0.0,0.0,0.0,0.002236
275,Erin Parker,24,Week 3,10,0,0,Erin,Parker,LA,0,...,0,0,0,0,1.0,0.0,0.0,0.0,0.0,0.002236
276,Jackie Topelli,23,Week 1,10,0,0,Jackie,Topelli,MN,0,...,0,0,0,0,1.0,0.0,0.0,0.0,0.0,0.002236
277,Jeanette Alvarez,27,Week 1,10,0,0,Jeanette,Alvarez,FL,0,...,0,0,0,0,1.0,0.0,0.0,0.0,0.0,0.002236
278,Jessica Devallo,32,Week 1,10,0,0,Jessica,Devallo,NY,0,...,0,0,0,0,1.0,0.0,0.0,0.0,0.0,-0.016589
279,Kate Brockhouse,24,Week 4,10,0,0,Kate,Brockhouse,South Carolina,0,...,0,0,0,0,1.0,0.0,0.0,0.0,0.0,0.002236
280,Linda Malek,33,Week 1,10,0,0,Linda,Malek,OH,0,...,0,0,0,0,1.0,0.0,0.0,0.0,0.0,-0.016589
281,Lindsay Smith,22,Week 1,10,0,0,Lindsay,Smith,KS,0,...,0,0,0,0,1.0,0.0,0.0,0.0,0.0,0.002236
282,Nicole Clary,26,Week 4,10,0,0,Nicole,Clary,SC,0,...,0,0,0,0,1.0,0.0,0.0,0.0,0.0,0.002236
283,Peyton Wright,24,Week 3,10,0,0,Peyton,Wright,Tennessee,0,...,0,0,0,0,1.0,0.0,0.0,0.0,0.0,0.002236
284,Stephanie Tipper,27,Week 4,10,1,1,Stephanie,Tipper,SC,0,...,0,0,0,0,0.0,1.0,0.0,0.0,0.0,0.059174
285,Stephanie Wilhite,23,Week 5,10,0,1,Stephanie,Wilhite,Kansas,0,...,0,0,0,0,0.0,1.0,0.0,0.0,0.0,0.103939
286,Susan Anderson,23,Week 2,10,0,0,Susan,Anderson,TX,0,...,0,0,0,0,1.0,0.0,0.0,0.0,0.0,0.002236
287,Tessa Horst,26,Winner,10,0,1,Tessa,Horst,California,1,...,0,0,0,0,0.0,1.0,0.0,0.0,0.0,0.103939
288,Tiffany Forester,27,Week 1,10,0,0,Tiffany,Forester,MN,0,...,0,0,0,0,1.0,0.0,0.0,0.0,0.0,0.002236
289,Tiffany Warren,28,Week 2,10,0,0,Tiffany,Warren,MA,0,...,0,0,0,0,1.0,0.0,0.0,0.0,0.0,0.002236
290,Tina Wu,26,Week 5,10,0,1,Tina,Wu,California,0,...,0,0,0,0,0.0,1.0,0.0,0.0,0.0,0.103939